### ISSUE TITLE
Year in pixels tab empty

### ISSUE THREAD

**Issue by queze1** [someretical/TheoreticalDiary#10]
**Describe the bug**
The year in pixels tab is empty.

**To Reproduce**
1. Add something to the diary
![Screenshot 2021-11-19 194720](https://user-images.githubusercontent.com/52340127/142593603-4e488534-dc3b-46c9-a78f-64bb39a853eb.png)

2. Click on "Year in pixels"
![Screenshot 2021-11-19 194924](https://user-images.githubusercontent.com/52340127/142593591-09b603c3-7da2-4a87-86d4-25340c921ae8.png)

**Expected behavior**
I expected something to be shown in the year in pixels tab,

**Comment by someretical** [comment]
Any day that does not have a rating on it will show up as blank. I will look into displaying a star background for starred days.
