### ISSUE TITLE
Remove "Are you sure you want to switch dates without saving" prompt if no changes were made

### ISSUE THREAD

**Issue by queze1** [someretical/TheoreticalDiary#12]
**Is your feature request related to a problem? Please describe.**
![Screenshot 2022-01-17 200143](https://user-images.githubusercontent.com/52340127/149739610-25095ac2-78c0-47b0-8b16-bec743cad2fc.png)
Switching dates for the first time always brings up the "Are you sure you want to switch dates without saving" prompt even if no changes have been made.

**Describe the solution you'd like**
Remove the prompt for this case.

**Comment by someretical** [comment]
This is actually an issue that I am fixing right now so hang in there.
