### ISSUE TITLE
Immediately update the calendar box when changes are made

### ISSUE THREAD

**Issue by queze1** [someretical/TheoreticalDiary#13]
**Is your feature request related to a problem? Please describe.**
![Screenshot 2022-01-17 200637](https://user-images.githubusercontent.com/52340127/149740190-0db743b6-9e21-4e22-acb7-b27b8b2b52a5.png)
It is slightly annoying that changes to the rating or special checkbox only update the calendar box's appearance after the update button is pressed.

**Describe the solution you'd like**
Update the box's appearance whenever changes are made to it.

**Comment by someretical** [comment]
I'm not going to be 'fixing' this since it makes sense from a logical perspective that the changes you have made should not appear anywhere else until you have actually saved them.
