### ISSUE TITLE
Remove render button on "Year in pixels"

### ISSUE THREAD

**Issue by queze1** [someretical/TheoreticalDiary#17]
**Is your feature request related to a problem? Please describe.**
The render button is redundant since rendering only needs to happen when the year is changed or the tab is loaded.

**Describe the solution you'd like**
Remove the render button and automatically rerender whenever the year is changed.

**Comment by someretical** [comment]
The render button is there if the user wants to manually change the year. The reason why it is this way is because it's a relatively expensive process to render all the buttons. You can check the source code in `src/gui/diarypixels.cpp` to see what I mean.

**Comment by queze1** [comment]
Automatically rendering once the user manually changing the year would be more convenient than manually changing the year and pressing the render button.

**Comment by someretical** [comment]
The thing is, you can't just switch to a completely different year without pasting the value in directly. So either you paste it in once and it updates, or it just keeps on updating as you change the place values one by one.
