### ISSUE TITLE
"Year in pixels" export should have an year indicator

### ISSUE THREAD

**Issue by queze1** [someretical/TheoreticalDiary#18]
**Is your feature request related to a problem? Please describe.**
![2022](https://user-images.githubusercontent.com/52340127/149743946-62f7ab43-9745-4f9b-8fdc-e3dfb080630b.png)
The "Year in pixels" export has no year indicator.

**Describe the solution you'd like**
Add a year indicator.
![2022](https://user-images.githubusercontent.com/52340127/149744124-ab76f004-b743-41ef-95e1-4150c5f999b6.png)
An example of an year indicator.

**Comment by someretical** [comment]
Not sure what you mean here:
![image](https://user-images.githubusercontent.com/29365738/149746575-f722ba00-f254-4c5b-af64-b2d134e033a0.png)
There is clearly a year edit box for me.
