### ISSUE TITLE
Allow the box in the entry tab to extend outwards

### ISSUE THREAD

**Issue by queze1** [someretical/TheoreticalDiary#7]
![Screenshot 2021-11-19 194020](https://user-images.githubusercontent.com/52340127/142592386-c743700d-e0c9-4874-afbe-29c77bc8a789.png)
The text box seems to leave a lot of unused space and only has room for a few words. I suggest enlarging it.

**Comment by someretical** [comment]
Due to how the scroll area is drawn internally, the large blank there will have to remain. If you put more text in your entries, they should expand to be longer. Also you can double click any entry with an ellipsis (...) at the end to expand the contents.
