### ISSUE TITLE
Fullscreen option please

### ISSUE THREAD

**Issue by queze1** [someretical/TheoreticalDiary#8]

**Comment by someretical** [comment]
In my opinion, I will definitely not be implementing full screen since I am almost certain it will just bring up even more bugs. There are several full screen modes on Windows alone and it may interfere with the lock timer. The being said, pull requests on this issue are welcome.

**Comment by someretical** [comment]
As of the current commit (35b736ba9264e883b2093048b26809d465deceac), all parts of the application have had high resolution scaling implemented. This means the content will do its best to expand upon the window being resized. This is as close to a 'full screen' feature as I will implement.

**Comment by someretical** [comment]
As of the current commit 585502902c9c679c8336d32b602b15294a897a2a, the app now remembers your window resolution and size from your last session. However, I've only confirmed this on Linux so far.

**Comment by queze1** [comment]
For Windows, the app is correctly remembering window resolution and size from the previous session. The high resolution scaling is working properly without the High DPI Scaling Override.
