### ISSUE TITLE
Statistics page empty

### ISSUE THREAD

**Issue by queze1** [someretical/TheoreticalDiary#9]
**Describe the bug**
The statistics page is empty.

**To Reproduce**
1. Add something to the diary
![Screenshot 2021-11-19 194720](https://user-images.githubusercontent.com/52340127/142593194-2afde2c6-bbcb-4b63-a6a0-427edf170315.png)
2. Click on statistics page
![image](https://user-images.githubusercontent.com/52340127/142593122-4a20ff88-7017-4a19-b9eb-038bcf06e50d.png)
![image](https://user-images.githubusercontent.com/52340127/142593853-b75a78df-d8fb-42ae-ab37-626e4552c6cb.png)
![Screenshot 2021-11-19 195155](https://user-images.githubusercontent.com/52340127/142593875-1eb59eb9-2357-4992-aa9b-83026a6b9ca8.png)

**Expected behavior**
I expected something to be shown on the statistics page.

**Comment by someretical** [comment]
This behavior is intentional since none of the days have ratings yet.
